Allow passing options from template to the MenuBuilder
KnpLabs/KnpMenu pull request #393
Opened 2024-06-07 22:24 UTC by gnat42

We were building a menu were we needed to pass some variables from our view to the knp_menu_render function. However in the builder for that menu, the $options array was always empty. With these changes the options successfully get passed through

2024-06-08 06:14 UTC, garak requested changes
Please add a test (or change an existing test) to cover this situation

2024-06-08 16:08 UTC, gnat42 commented
Hello, I took a second look and noticed additional locations where the options wouldn't make their way to the MenuBuilder so made more modifications and added tests to cover the modified methods.

2024-06-09 05:11 UTC, garak approved these changes

2024-06-14 15:53 UTC, garak commented
On a closer look, and after briefly discussing with stof, the idea seems not quite good.
The same change was already proposed in the past, and it was rejected, see for example PR #90 and #337

2024-06-18 15:21 UTC, gnat42 commented
OK, so can you explain how the docs show passing options to your menu builder but that's not actually possible? Did we mis-understand the docs or how to do this? It seems like a bug but I don't know enough to know what should be happening.

2024-06-18 15:34 UTC, stof commented
@gnat42 passing options from the template to the menu builder is possible when using the `knp_menu_get` Twig function to get the menu instance.

2024-06-19 14:39 UTC, gnat42 commented
Thanks @stof much appreciated! 

I'll look to see if a PR for the docs are appropriate to clarify how to do this and submit if its warranted.

2024-06-19 14:39 UTC, closed without merging